version: '2'
services:
  elasticsearch2:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
      ulimits:
        memlock:
          soft: -1
          hard: -1
      # This value is suitable for dev. Set higher for production.
      mem_limit: ${ES_MEM_LIMIT}
      ports:
          - 9300:9300
      volumes:
        - ${TWEETSETS_DATA_PATH}/elasticsearch:/usr/share/elasticsearch/data
      networks:
        - tweetsets
      environment:
        - cluster.name=tweetsets-cluster
        - bootstrap.memory_lock=true
        - network.host=_global_
        - transport.tcp.port=9300
        - "ES_JAVA_OPTS=-Xms${ES_JAVA_MEM} -Xmx${ES_JAVA_MEM}"
        - "discovery.zen.ping.unicast.hosts=${MASTER_HOST}"
        - xpack.security.enabled=false
        - TZ
networks:
  tweetsets: