version: '2'
services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
      logging:
          driver: json-file
          options:
              max-size: ${DOCKER_LOG_MAX_SIZE}
              max-file: ${DOCKER_LOG_MAX_FILE}
      ulimits:
        memlock:
          soft: -1
          hard: -1
      # This value is suitable for dev. Set higher for production.
      mem_limit: ${ES_MEM_LIMIT}
      ports:
          - 9300:9300
          - 9200:9200
      volumes:
        - ${TWEETSETS_DATA_PATH}/elasticsearch:/usr/share/elasticsearch/data
      networks:
        - tweetsets
      environment:
        - cluster.name=${CLUSTER_NAME}
        - bootstrap.memory_lock=true
        - network.host=_eth0_
        - network.publish_host=${HOSTNAME}
        - "ES_JAVA_OPTS=-Xms${ES_JAVA_MEM} -Xmx${ES_JAVA_MEM}"
        - discovery.zen.ping.unicast.hosts=${PRIMARY_HOSTNAME}
        - node.master=${MASTER}
        - TZ
        # added for 7.9.2
        - cluster.initial_master_nodes=${PRIMARY_HOSTNAME}
        - node.name=${HOSTNAME}
      restart: always
  spark-worker:
      image: gwul/tweetsets-spark
      command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://${SPARK_MASTER_HOSTNAME}:7101
      hostname: ${HOSTNAME}
      logging:
          driver: json-file
          options:
              max-size: ${DOCKER_LOG_MAX_SIZE}
              max-file: ${DOCKER_LOG_MAX_FILE}
      environment:
          SPARK_WORKER_CORES: ${SPARK_CORES}
          SPARK_WORKER_MEMORY: ${SPARK_MEMORY}
          SPARK_PUBLIC_DNS: ${HOST_IP}
          SPARK_LOCAL_HOSTNAME: ${HOSTNAME}
          SPARK_IDENT_STRING: ${HOSTNAME}
          SPARK_WORKER_PORT: 7001
          SPARK_WORKER_WEBUI_PORT: 7002
      ports:
          - 7001:7001
          - 7002:7002
          - 7003-7028:7003-7028
      networks:
        - tweetsets
      volumes:
        - ${DATASET_PATH}:/dataset
      restart: always
networks:
  tweetsets:
